DataDog/datadog-cluster-monitoring-pivotal-tile

tile/tile.yml

* Org Data Collection Interval
* Batch Sizes for V3 API

Add form fields for new options

---

tile/tile.yml

Remove PCF references as part of Pivotal rebranding
See above
Manual review  | grep

remove PCF references

---

tile/tile.yml

Add Datadog Cluster Agent Bosh release to the tile

---

tile/tile.yml

Disable NPM with system probe by default

---

tile/tile.yml

Add note about additional instance for Datadog Cluster Agent

---

tile/tile.yml

Add the possibility to automatically generate certificate and private key using Opsman Root CA, or to manually input custom ones.
It simplifies the configuration of the cluster agent by doing the automatic configuration by default.
Users who needed to provide a custom CA, and manually generate the certificate and private key with 4.0.0 will need to redo this part of the configuration of the tile and provide it again.
`Yes`
`No`

Simplify configuration of cluster agent by generating certificate and private key automatically

---

tile/tile.yml

Add nozzle configuration options for metadata collection

---

tile/tile.yml

Add two options in the `Datadog Cluster Agent` configuration form to enable collecting audit events from the CC API by configuring the Cloud Foundry API integration as a cluster check.

Add ability to configure the Cloud Foundry API integration as a cluster check

---

tile/tile.yml

This reverts commit de1214f1f505b2c0b4e24e0debbfe7b4b0f3619b.
Reverts #25 as it doesn't work due to issue in opsman.

Revert "Simplify configuration of cluster agent by generating certificate and private key (#25)

---

tile/tile.yml

Avoid specifying bosh link when cluster agent disabled

---

tile/tile.yml

Removes the use of Bosh link to resolve the cluster agent address and defines a DNS name instead.
This effectively fixes the issues with deployment order and removes the need for a 2-step deployment when enabling the cluster agent feature.

Use DNS alias instead of bosh link

---

tile/tile.yml

Add site field, and rework a bit the other API URL field, and add a field to specify the nozzle API URL. This should now allow users to properly send all data (metrics AND process/NPM data) to a different datacenter, like EU.
Existing user shouldn't be affected by the addition of the new fields, as setting the main `API URL` field will keep the same behavior.

Add field for customizing API site and properly sending data to other Datadog regions

---

tile/tile.yml

Support TKGI kubernetes control plane monitoring by specifying a second Datadog Agent add-on, with configured integrations for control plane.
Also fixes the release name `kube-scheduler` in the placement rules

Add TKGI kubernetes control plane monitoring

---

tile/tile.yml

Add option to append VM UUID to generated friendly hostnames

---

tile/tile.yml

Added *cloud_foundry_bbs_env_include* and *cloud_foundry_bbs_env_exclude* input fields

Add option to send application environment variables as custom container tags

---

tile/tile.yml

Add option to collect containers only with the Process Agent

---

tile/tile.yml

related to https://github.com/DataDog/datadog-cluster-agent-boshrelease/pull/18

Add option to poll Cloud Foundry API for more advanced container tagging

---

tile/tile.yml

Reverts DataDog/datadog-cluster-monitoring-pivotal-tile#43

Revert "Revert "Add option to send application environment variables as custom container tags""

---

tile/tile.yml

Related to https://github.com/DataDog/datadog-agent-boshrelease/pull/149

Add inputs to configure custom URLs for process, APM and logs

---

tile/tile.yml

SSIA 
Related to https://github.com/DataDog/datadog-agent-boshrelease/pull/150

Add `no_proxy_nonexact_match` configuration option

---

tile/tile.yml

Give more control to the user on where the agent gets deployed.
Adds two tabs to configure the `include` and `exclude` placement rules for the Datadog Agent BOSH add-on.
Sets the default to the current placement rules that target every linux VM.
Manually tested on lab environment

Add configuration forms for Datadog Agent Bosh addon placement rules

---

tile/tile.yml

See also https://github.com/DataDog/datadog-cluster-agent-boshrelease/pull/20

Add property to specify ulimit for number of open file descriptors

---

tile/tile.yml

Related to https://github.com/DataDog/datadog-cluster-agent-boshrelease/pull/21

Add configuration option for CC API list app endpoint batch size

---

tile/tile.yml

Add option to force use of TLS 1.2

---

tile/tile.yml

SSIA, see https://github.com/DataDog/datadog-agent-boshrelease/pull/155

Add option to collect monit children processes

---

tile/tile.yml

Add missing option to enable advanced tagging in the cluster agent

---

tile/tile.yml

See PCF TAS 3.0 Breaking changes: https://docs.pivotal.io/application-service/3-0/release-notes/runtime-rn.html#jammy-instance-groups

Add support for ubuntu-jammy stemcell

---

tile/tile.yml

Update label of `refresh_on_cache_miss` property

---

CHANGELOG.md
tile/tile.yml

Release 5.4.1

---

CHANGELOG.md
tile/tile.yml

Remove beta suffix from agent bosh version release number

---

tile/tile.yml

- Set the main `stemcell_criteria` back to  `ubuntu-xenial` for the current release.
To ensure better compatibility with all PCF TAS versions ( `< 3.0` and `> 3.0`), we'll switch back to using `ubuntu-xenial` as main `stemcell_criteria` for the current release.
We still include `ubuntu-jammy` in the stemcell inclusion rules , which will allow the tile to install the `datadog-agent-boshrelease` on jammy stemcells as well.
- Deployed on PCF TAS 3.0 ✅ 
- Deployed on PCF TAS 2.13 ✅ 
- Deployed on PCF TAS 2.11 ✅

Use `ubuntu-xenial` stemcells

---

CHANGELOG.md

Release 5.5.0 update

---

scripts/prepare.sh

Bump versions and remove tile install in the prepare script

---

tile/tile.yml

SSIA
https://github.com/DataDog/datadog-cluster-monitoring-pivotal-tile/pull/103

Disable remote configuration by default

---

tile/tile.yml

Add options to support the new nozzle properties related to logs collection.

Add options for nozzle logs collection

---

tile/tile.yml

Fix BPM memory optional values with default error

---

tile/tile.yml

Fixes another property which had both optional set to `true` and a default value, these were introduced from 5.8.0 -> 5.9.0.
See https://github.com/DataDog/datadog-cluster-monitoring-pivotal-tile/issues/109
Removes `optional: true` attribute from all the properties added in 5.9.0 (BPM properties and Nozzle logs collection properties).

Fix optional and default value error message
